/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/appointments-modal`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/jenny-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/provider-selection` | `/provider-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor-detail)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(personal-info)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Home/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home/plan`; params?: Router.UnknownInputParams; } | { pathname: `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home/reports`; params?: Router.UnknownInputParams; } | { pathname: `/Home/today-schedule`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/appointments-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/jenny-schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/provider-selection` | `/provider-selection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(doctor-detail)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(personal-info)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/plan`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/today-schedule`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/appointments-modal${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/jenny-schedule${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/provider-selection${`?${string}` | `#${string}` | ''}` | `/provider-selection${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(doctor-detail)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(personal-info)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Home/appointments${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/Home/plan${`?${string}` | `#${string}` | ''}` | `/Home/profile${`?${string}` | `#${string}` | ''}` | `/Home/reports${`?${string}` | `#${string}` | ''}` | `/Home/today-schedule${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/appointments-modal`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/jenny-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/provider-selection` | `/provider-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(doctor-detail)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(personal-info)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Home/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home/plan`; params?: Router.UnknownInputParams; } | { pathname: `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home/reports`; params?: Router.UnknownInputParams; } | { pathname: `/Home/today-schedule`; params?: Router.UnknownInputParams; };
    }
  }
}
